### ISSUE TITLE
BERT results

### ISSUE THREAD

**Issue by dy-ux** [BillKiller/GAIR-SLU#2]
Will the result be very low after replacing Stack Propagation with BERT?

**Comment by BillKiller** [comment]
We discovered that simply replacing the embedding with BERT often results in unstable model performance, which could be due to the selection of hyperparameters. Therefore, alongside replacing the embedding with BERT, we added or removed some modules, such as LSTM and Self-Attention, and performed hyperparameter tuning, which allowed us to achieve scores higher than those of w2v.
